### ISSUE TITLE
Launch tracking

### ISSUE THREAD

**Issue by kytrinyx** [exercism/cobol#1]
This issue helps keep track of the tasks you're working on towards launching this track.

The next steps are:

- [x] [Join our community](https://exercism.org/docs/building/tracks/new/join-our-community)
- [x] [Select programming language variant](https://exercism.org/docs/building/tracks/new/select-programming-language-variant) (if applicable)
- [x] [Select testing framework](https://exercism.org/docs/building/tracks/new/select-testing-framework)
- [x] [Add the first exercise](https://exercism.org/docs/building/tracks/new/add-first-exercise)
- [x] [Add initial exercises](https://exercism.org/docs/building/tracks/new/add-initial-exercises)
- [x] [Setup Continuous Integration](https://exercism.org/docs/building/tracks/new/setup-continuous-integration)
- [x] [Prepare for launch](https://exercism.org/docs/building/tracks/new/prepare-for-launch)
- [x] [Find Maintainers](https://exercism.org/docs/building/tracks/new/find-maintainers)
- [x] [Launch!](https://exercism.org/docs/building/tracks/new/launch)
- [x] [Implement tooling](https://exercism.org/docs/building/tracks/new/implement-tooling)
- [x] [Prepare for open source contributions from strangers](https://exercism.org/docs/building/tracks/new/prepare-for-contributions)

Once you've finished a task, you can check them in this list.

## Questions

Please ask if you have any questions or if anything is confusing!

**Comment by TriAttack238** [comment]
So, where do I learn how to make exercises in general? Do I need to download exercism to my machine?

**Comment by KTSnowy** [comment]
Hey @TriAttack238 I think this link might help:
https://exercism.org/docs/building/tracks/new/add-first-exercise

**Comment by TriAttack238** [comment]
Wait, can you create and run a function in COBOL without having to put it inside of the procedure division of the main program?

**Comment by TriAttack238** [comment]
In any case, I’ll be right on these initial exercises when I have the time.

**Comment by KTSnowy** [comment]
AFAIK that's not possible with COBOL, you need at least the ID division and the procedure division.

**Comment by KTSnowy** [comment]
I think we can make it work, well find a way. It is different from anything else so it's really worth it to teach this, even if it's just to give a different perspective.

**Comment by TriAttack238** [comment]
Let’s just warn the students not to touch any capitalized words at the start.

**Comment by KTSnowy** [comment]
One way would be to make a static identification division that's used for every exercise.

And the code that the user writes would be concatenated to it.

Or we teach the students about the division and that they're necessary.

And warn them about removing it, like you said.

**Comment by KTSnowy** [comment]
It's also worth it to note that modern COBOL doesn't require capitalized keywords, so warning the students about those might not work.

**Comment by KTSnowy** [comment]
Another issue would be which format do we teach to the students on this track?

COBOL has fixed format and free format. 

Fixed has very specific rules of where certain things should go, like line numbers, comments, divisons and sections.

Free is more like modern languages, where you don't need to explicitly write line numbers and it's more relaxed on indentation rules.

**Comment by TriAttack238** [comment]
> It's also worth it to note that modern COBOL doesn't require capitalized keywords, so warning the students about those might not work.

But capitalizing keywords is still in best practices. For example in the Python track constants are taught with capitalized names, even though Python doesn’t actually have constants.

**Comment by TriAttack238** [comment]
> Another issue would be which format do we teach to the students on this track?
> 
> COBOL has fixed format and free format.
> 
> Fixed has very specific rules of where certain things should go, like line numbers, comments, divisions and sections.
> 
> Free is more like modern languages, where you don't need to explicitly write line numbers and it's more relaxed on indentation rules.

I’m aware of the differences, but it’s a tough question. I personally prefer free, and it’s in the standard, but it would make older code harder to understand if it’s learned first. However, unit tests technically only care about the result, not how, so it might be possible to talk about both.

**Comment by KTSnowy** [comment]
> However, unit tests technically only care about the result, not how, so it might be possible to talk about both.

Yea we should talk about both. If they encounter COBOL in a real world situation it's possible it'll still use fixed format.

**Comment by TriAttack238** [comment]
Something else to iron out is if we’re making this a learning mode course we need a track of concepts that creates a smooth learning curve and makes sense.

**Comment by KTSnowy** [comment]
Maybe we could teach according to the order of the divisions like this:

identification division...
environment division...
data division...
and then procedure division...

Not sure if that would make sense for a new student though.

**Comment by TriAttack238** [comment]
No, I don’t think so, that would be like having a driving class and starting by talking about the history of roads. The course should get the students to start doing things as soon as possible. We’re trying to avoid the mistakes of the book here.

**Comment by KTSnowy** [comment]
```
identification division.
    program-id. hello.

procedure division.
    display "Hello, World!".
    stop run.
```

This is how would it would look like if we start with free format for the hello world.

**Comment by KTSnowy** [comment]
That sounds good, so we should start with the basics first?

**Comment by TriAttack238** [comment]
Yes

**Comment by KTSnowy** [comment]
```cobol
identification division.
  program-id. exercism-variables.

data division.
  working-storage section.
    01 ws-var pic x(13) value "Hello, World!".

procedure division.
  display ws-var.
  stop run.
```

This is how a hello world would look with variables.

**Comment by KTSnowy** [comment]
It would be too confusing for students to start with user defined functions. They have their own divisions as well.

**Comment by TriAttack238** [comment]
Then just have a stub with all that stuff in the first exercise

**Comment by TriAttack238** [comment]
If you look at the website, every track starts with a complete function returning “Goodbye, Mars!” the student changes to “Hello, World!”. So, we just do that in COBOL

**Comment by KTSnowy** [comment]
> every track starts with a complete function returning

Issue is that COBOL user defined functions would be too complex for starting students who don't understand COBOL. We can start with the basics first, COBOL procedure division can be considered a C-like Main function.

If you use `procedure division returning ws-variable.` it returns a value, but that's not needed if we're just displaying "Hello, World!".

**Comment by TriAttack238** [comment]
But we don’t need to teach the syntax for the first one, the first exercise is changing the returned literal and that’s it. I think the return part is crucial for unit testing. Just log onto a track and check.

**Comment by TriAttack238** [comment]
But yeah if we can trim it down that still works.

**Comment by KTSnowy** [comment]
Hmmmm we can try, I'll see if I can make a working user defined function program. I'm afraid of scaring people when they see it hahah.

**Comment by iHiD** [comment]
Excited to see this underway. Thanks everyone!

Some cc's:
- @erikschierboom for helping y'all understand about how to get everything running happily in Exercism's env
- @joshgoebel for HighlightJS
- @axtens as he's been planning this for a while and should be co-leading on it 🙂 

I've also enabled Pull Requests as a requirement in this repo as there's multiple people working on it..

**Comment by iHiD** [comment]
Also, it'd be great if you'd organise a chat with @jonathandmiddleton to get to know your way around Exercism's community of maintainers.

**Comment by KTSnowy** [comment]
> But yeah if we can trim it down that still works.

```cobol
IDENTIFICATION DIVISION.
  FUNCTION-ID. EXERCISMFUN.
DATA DIVISION.
  LINKAGE SECTION.
    01 LS-VAL PIC 9(1) VALUE 1.
PROCEDURE DIVISION RETURNING LS-VAL.
    DISPLAY "Hello, World!".
    GOBACK.
END FUNCTION EXERCISMFUN.

IDENTIFICATION DIVISION.
  PROGRAM-ID. HELLO.
ENVIRONMENT DIVISION.
  CONFIGURATION SECTION.
    REPOSITORY. FUNCTION EXERCISMFUN.
PROCEDURE DIVISION.
  DISPLAY FUNCTION EXERCISMFUN()
STOP RUN.
```
This is an example of a used defined function in COBOL, I'm sure it could be written in a better way, but documentation on this is really really bad at explaining how exactly it works. The function is the first thing there and it displays "Hello, World!" and returns 1. The second thing is for calling that user defined function.

I tested it with gnuCOBOL and it works.

This is another reason why we really need to build this Exercism track, COBOL documentation is not really that good right now.

**Comment by KTSnowy** [comment]
Hey @iHiD, thanks for joining us here.

I'll certainly ask @joshgoebel about how HighlightJS, currently there doesn't seem to be a package for COBOL Highlighting for HLJS. Maybe he could help us with that?

**Comment by axtens** [comment]
I'm in UTC+8 and still at breakfast. I've been praying for a time such as this. I will get back to you all later in the day.

**Comment by KTSnowy** [comment]
Hey @axtens, thanks for joining us. 

Time to make some good and easy to understand COBOL documentation? Can't wait to see this working on Exercism.

**Comment by TriAttack238** [comment]
I mean, if COBOL is like English, then we just need to make an English textbook. That’s not too hard, right?

**Comment by KTSnowy** [comment]
Might not be that simple, it would be like making a complete English textbook when all current English textbooks are not complete or don't explain things clearly.

**Comment by TriAttack238** [comment]
That’s when we consult the giant book(the standard).

**Comment by TriAttack238** [comment]
Oh yeah, is there a way to have "debrief" documents? COBOL has a lot of aspects where you can follow the book and do a thing but not understand at all what happened. For example, the "hello world" assignment will have quite a bit of writing that a student may want an explanation on, like the whole concept of divisions and sections.

**Comment by TriAttack238** [comment]
In any case, I've started to learn markdown in full.

**Comment by KTSnowy** [comment]
![Screen Shot 2022-07-12 at 02 42 23](https://user-images.githubusercontent.com/73310001/178417306-5e47cb5a-6122-402d-a5c2-9bd2153f9253.png)
I'm working on the highlightjs package. This might take a while.

**Comment by KTSnowy** [comment]
But this made me realize how many keywords are actually non-standard. A lot of tutorials and videos use keywords that are not present in the standard.

**Comment by TriAttack238** [comment]
_Interesting_. Tomorrow I'll try to figure out the first test in my own branch. What testing framework are we using again?

**Comment by KTSnowy** [comment]
@TriAttack238 I think it's this one:
https://github.com/openmainframeproject/cobol-check

Hey @axtens, is this the testing framework that we'll be using?

**Comment by axtens** [comment]
That's the one. If you join #maintaining-cobol in Exercism' s Slack you can discuss that decision with Sven

**Comment by axtens** [comment]
I've emailed you an invitation

**Comment by kytrinyx** [comment]
@KTSnowy I accidentally sent you an invitation to the wrong workspace /facepalm. I revoked the invitation, but you should be able to get into the exercism-team workspace that @axtens invited you too.

**Comment by joshgoebel** [comment]
@KTSnowy It should be reasonably easy to create a new 3rd party highlighting module for Cobol.  Minimally you could start with just a huge list of keywords. (which it looks like you already have)  Happy to help with any specific questions.

See our docs:

- https://github.com/highlightjs/highlight.js/blob/main/extra/3RD_PARTY_QUICK_START.md
- https://highlightjs.readthedocs.io/en/latest/language-guide.html

Also perhaps just browse thru the built-in languages till you find one of the simpler ones... seeing some existing languages can give you an idea of what you're looking to accomplish.

---

Is Cobol the language still undergoing many changes today or is it mostly static?

**Comment by KTSnowy** [comment]
> Is Cobol the language still undergoing many changes today or is it mostly static?

It's still receiving updates, the latest 202x standard draft is in the voting phase.

**Comment by KTSnowy** [comment]
https://github.com/otterkit/highlightjs-cobol

I made this, not if it's working though. I'll test it later.

**Comment by KTSnowy** [comment]
I used the other highlightjs repos as a template for the readme and contributing files.

**Comment by KTSnowy** [comment]
https://www.npmjs.com/package/highlightjs-cobol

**Comment by KTSnowy** [comment]
![Capture](https://user-images.githubusercontent.com/73310001/178538725-1b09041e-3435-4f80-b1e6-742e194f8063.PNG)

**Comment by joshgoebel** [comment]
@KTSnowy You can do operators, but not how you had it before... every item in `contains` has to be a full mode... so a very simple rule would just have a scope and match:

```
contains: [
  { scope: "operator", match: /\+/ } ]
```

So you'd make a bunch of separate rules - you could also do this programmatically - it's just JS, but most commonly you'd probably do this with the regex helpers:

```js
OPERATORS = [ /*array of operators */ ]

// later
contains: [
  { scope: "operator", match: regex.either(...OPERATORS) } ]
```

Depending on your operators they may need special escaping... I'd have to double check.  `regex.either` is just a nice wrapper that builds a `(x|y|x)` regex.

**Comment by joshgoebel** [comment]
If your keywords are going to include `-` you need to use `keywords.$pattern` and specify a regex that is able to match *potential* keywords... the default is like `\w*` or something, which doesn't include `-`.

**Comment by TriAttack238** [comment]
Ok, I'm opening up a new branch. @KTSnowy, you already merged your Json changes, right?

**Comment by KTSnowy** [comment]
@TriAttack238 we already did, the config.json should be working correctly now.

**Comment by KTSnowy** [comment]
I'm now working on fixing the issues with the syntax highlighter.

**Comment by TriAttack238** [comment]
Nice, I'll see if I can get this first test working or at least add some concepts.

**Comment by TriAttack238** [comment]
Can I get permission to make a branch please?

**Comment by KTSnowy** [comment]
> Can I get permission to make a branch please?

We have to ask @kytrinyx I think. I don't have permission to add you.

**Comment by KTSnowy** [comment]
@TriAttack238 I created a branch for you:
https://github.com/exercism/cobol/tree/triattack238-devbranch

**Comment by KTSnowy** [comment]
See if you can work on this branch

**Comment by TriAttack238** [comment]
Nope, still can't change the branch

**Comment by TriAttack238** [comment]
Please?

**Comment by SleeplessByte** [comment]
@KTSnowy is it possible for @TriAttack238 to fork the branch, work from there, and push back using a PR? This could help in the intermediate.

**Comment by TriAttack238** [comment]
That might not be a bad idea.

**Comment by KTSnowy** [comment]
@SleeplessByte I think it could work.

**Comment by iHiD** [comment]
<img width="521" alt="Screenshot 2022-07-13 at 02 15 49" src="https://user-images.githubusercontent.com/286476/178627536-968d96c8-fb21-4701-9b17-b8a84dd6938f.png">

I invited @TriAttack238 yesterday but the invite has not yet been accepted. But using forks as @SleeplessByte suggested is a good idea anyway.

**Comment by TriAttack238** [comment]
Sorry, forgot that the app doesn't show certain notifications.

**Comment by TriAttack238** [comment]
Alright, KT finished the first exercise so I'm going to check off the box.

**Comment by TriAttack238** [comment]
Hey, should we have example code snippets in fixed or free format?

**Comment by KTSnowy** [comment]
> Hey, should we have example code snippets in fixed or free format?

I think we should mostly use free format, and talk about fixed format and it's rules separately.

This is because free format is more similar to how modern languages work, and fixed format has very strict rules that could be frustrating for students if they had to use it for most exercises.

**Comment by TriAttack238** [comment]
Got it. I was wondering because your first exercise stub is in fixed format.

**Comment by KTSnowy** [comment]
IIRC gnuCOBOL uses fixed format by default, so we might have to pass the -free command line option to it for most exercises.

**Comment by TriAttack238** [comment]
I personally just include 'source FREE' in my programs, but that also works.

**Comment by KTSnowy** [comment]
> I was wondering because your first exercise stub is in fixed format.

The hello world example? It's using free format, but without the compiler directive.

**Comment by TriAttack238** [comment]
Ah, I see now.

**Comment by KTSnowy** [comment]
I used the -free command line option so that I don't have to write free format on every file.

**Comment by TriAttack238** [comment]
Wait, KT, on your test the GOBACK keyword is before the return variable is initialized. So it doesn't activate immediately?

**Comment by TriAttack238** [comment]
Also, should we teach students to add STOP RUN and/or STOPing the program? It's only useful when using open subprocedures, but it might be important as a best practice.

**Comment by KTSnowy** [comment]
Alright, so at first that sounded a bit weird so I checked the hello-world example and it seems to have been changed from the one I uploaded yesterday.

And you're right, the one currently there doesn't do anything since the goback is the first clause in the procedure division. And it should be STOP RUN to return control back to the OS, goback is only for subprograms and user defined functions to return control to the calling program.

**Comment by KTSnowy** [comment]
@TriAttack238, STOP RUN is used when you need to completely stop execution and return control back to the OS, GOBACK is when you want to stop execution of a subprogram or user defined function and return control to the calling program.

**Comment by TriAttack238** [comment]
As I assumed, and GOBACK also returns the current value of the promised variable, right?

**Comment by TriAttack238** [comment]
Alright, my branch now has its first full draft of the introduction. Feel free to check it out.

**Comment by KTSnowy** [comment]
GOBACK doesn't return any values, to return a value you need to define it on the procedure division like this: `procedure division returning $VARIABLE$.`

**Comment by KTSnowy** [comment]
This will return a value when exiting the program.

**Comment by TriAttack238** [comment]
Ok, got it.

**Comment by KTSnowy** [comment]
Hey @axtens, what happened with the previous hello world example? The current one is using fixed format and it immediately uses the goback statement.

**Comment by KTSnowy** [comment]
I added support for number highlighting in version 0.2.12 of the highlightjs package
Here's a test example:
https://codepen.io/ktsnowy/pen/vYRXxov

**Comment by TriAttack238** [comment]
Wait, how do use that in a markdown file?

**Comment by KTSnowy** [comment]
@TriAttack238 could you check if it's possible to add HTML to the exercises markdown?

**Comment by KTSnowy** [comment]
GitHub does have it's own syntax highlighting, but I'm not sure if that will work on Exercism because they ask about highlightjs when requesting for a new track.

**Comment by TriAttack238** [comment]
Makes sense

**Comment by KTSnowy** [comment]
I'm looking at Go's track right now to see if I can figure out how it works

**Comment by KTSnowy** [comment]
@TriAttack238 from what I can tell it works just like Github with a "cobol" at the start of the code block, I made a pull request to update the highlightjs_language in the config.json

**Comment by TriAttack238** [comment]
Ok, so I won't need to update that part

**Comment by TriAttack238** [comment]
I'll check it out when I have time

**Comment by joshgoebel** [comment]
> Do we need to make a pull request to add the NPM package?

Probably to the bowels of Exercism web app somewhere, yes.

**Comment by TriAttack238** [comment]
Maybe something related to app/javascript/utils/highlight.ts in the website repo.

**Comment by TriAttack238** [comment]
Ok, for the language docs what is the difference between Learning.md and Resources.md? The TODO is basically the same.

**Comment by TriAttack238** [comment]
Alright, I'm putting in a pull request to merge my branch with main. I basically just wrote a lot of text, so please check it out.

**Comment by iHiD** [comment]
> Exercism needs to add the NPM package and then register the language with Highlight.js - then it should work the same as all the built-in grammars.

@ErikSchierboom :)

**Comment by iHiD** [comment]
> Ok, for the language docs what is the difference between Learning.md and Resources.md? The TODO is basically the same.

Does https://exercism.org/docs/building/tracks/docs help?

**Comment by TriAttack238** [comment]
Hmm, not really, but I think I understand the difference now. On the other hand, this one commit to add "basics" to config.json is taking forever.

**Comment by TriAttack238** [comment]
Hmm, normal commits such as changing the markdown files are quick, so it must be only changing json. Odd.

**Comment by TriAttack238** [comment]
Nevermind, I just have to used the command line instead of the vscode buttons.

**Comment by ErikSchierboom** [comment]
I submitted a PR to add highlightjs syntax highlighting for cobol: https://github.com/exercism/website/pull/2766

**Comment by ErikSchierboom** [comment]
We'll have @taiyab come up with one then.

**Comment by KTSnowy** [comment]
OpenAI just gave me access to DALL-E today, it's their text prompt image generator AI.

Maybe that's something we can use to generate illustrations for the track?

"Modern problems require modern solutions"

**Comment by TriAttack238** [comment]
We could make the logo a punch card.

**Comment by KTSnowy** [comment]
But why a punch card?

**Comment by KTSnowy** [comment]
But I don't think a punch card would be a good idea for this track, it would reinforce the idea that COBOL is an old, outdated language that only runs on punch cards.

**Comment by TriAttack238** [comment]
I guess with object oriented patterns it could conceivably do anything.

**Comment by KTSnowy** [comment]
I'm also really really bad at design so I won't we able to come up with a logo.

Does anyone here have logo design experience?

**Comment by junedev** [comment]
I'm leaving a boring suggestion: Instead of trying to design an unofficial logo, maybe just pick a font and a color and have a logo with just the name like the ABAP track.
![image](https://user-images.githubusercontent.com/12543047/179299909-2f8fb457-1b64-4579-ba9a-95bca5b06524.png)

**Comment by iHiD** [comment]
I think Erik answered this here: https://github.com/exercism/cobol/issues/1#issuecomment-1185716975

**Comment by TriAttack238** [comment]
It looks like the logo is in good hands.

**Comment by TriAttack238** [comment]
Ok, I'm trying to squash my commits for a pull request but while I was rebasing I accidentally did this:
`$ git commit'
> exit
> 
> end
> exit N
> 
> q
> :q
> break
> `

How do I break out of ">"?

**Comment by KTSnowy** [comment]
> How do I break out of ">"?

I think you'll have to use Ctrl-C to exit.

**Comment by TriAttack238** [comment]
Ok, thanks

**Comment by kotp** [comment]
> > How do I break out of ">"?
> 
> I think you'll have to use Ctrl-C to exit.

Instead of `control-c` as the first instinct, `control-d` (End of Data) is probably a better choice.

**Comment by TriAttack238** [comment]
Thanks! As you can see, I have very little experience with command line interfaces.

**Comment by taiyab** [comment]
@KTSnowy I like the punchcard idea for the logo, so I'll be updating it later with that. At the moment, I've just done a temporary placeholder one.

**Comment by axtens** [comment]
We are live!

**Comment by kotp** [comment]
We should close this issue, and open issues that came up from completing this one, such as updating the logo, for example.
